# Generated by Django 5.1.4 on 2026-05-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary_color", models.CharField(default="#3b82f6", max_length=7)),
                ("secondary_color", models.CharField(default="#ffffff", max_length=7)),
                ("stadium_name", models.CharField(default="", max_length=100)),
                ("reputation", models.FloatField(default=50.0)),
                ("valuation", models.BigIntegerField(default=1000000)),
                ("is_user_controlled", models.BooleanField(default=False)),
                ("is_for_sale", models.BooleanField(default=True)),
                ("balance", models.BigIntegerField(default=500000)),
                ("transfer_budget", models.BigIntegerField(default=0)),
                ("weekly_wages", models.BigIntegerField(default=0)),
                ("weekly_staff_wages", models.BigIntegerField(default=0)),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "LOCAL"),
                            ("BILLIONAIRE", "BILLIONAIRE"),
                            ("CORPORATE", "CORPORATE"),
                            ("FAN_OWNED", "FAN_OWNED"),
                        ],
                        default="LOCAL",
                        max_length=20,
                    ),
                ),
                (
                    "board_expectations",
                    models.CharField(
                        choices=[
                            ("CHAMPIONS", "CHAMPIONS"),
                            ("PROMOTION", "PROMOTION"),
                            ("PLAYOFFS", "PLAYOFFS"),
                            ("TOP_HALF", "TOP_HALF"),
                            ("MID_TABLE", "MID_TABLE"),
                            ("AVOID_RELEGATION", "AVOID_RELEGATION"),
                        ],
                        default="MID_TABLE",
                        max_length=30,
                    ),
                ),
                ("board_patience", models.IntegerField(default=60)),
                ("board_confidence", models.IntegerField(default=70)),
                ("fan_confidence", models.IntegerField(default=70)),
                (
                    "formation",
                    models.CharField(
                        choices=[
                            ("4-4-2", "4-4-2"),
                            ("4-3-3", "4-3-3"),
                            ("3-5-2", "3-5-2"),
                            ("4-2-3-1", "4-2-3-1"),
                            ("5-4-1", "5-4-1"),
                            ("4-4-2_DIAMOND", "4-4-2_DIAMOND"),
                        ],
                        default="4-4-2",
                        max_length=20,
                    ),
                ),
                (
                    "tactics",
                    models.CharField(
                        choices=[
                            ("POSSESSION", "POSSESSION"),
                            ("HIGH_PRESSING", "HIGH_PRESSING"),
                            ("COUNTER_ATTACK", "COUNTER_ATTACK"),
                            ("DEFENSIVE", "DEFENSIVE"),
                            ("WING_PLAY", "WING_PLAY"),
                            ("DIRECT", "DIRECT"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                (
                    "season_target",
                    models.CharField(
                        choices=[
                            ("CHAMPIONS", "CHAMPIONS"),
                            ("PROMOTION", "PROMOTION"),
                            ("PLAYOFFS", "PLAYOFFS"),
                            ("TOP_HALF", "TOP_HALF"),
                            ("MID_TABLE", "MID_TABLE"),
                            ("AVOID_RELEGATION", "AVOID_RELEGATION"),
                        ],
                        default="MID_TABLE",
                        max_length=30,
                    ),
                ),
                ("starting_lineup", models.JSONField(default=dict)),
                ("culture", models.JSONField(default=list)),
                ("rivals", models.JSONField(default=list)),
                ("history", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tier", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
                ("reputation", models.IntegerField(default=50)),
                ("prize_money_champion", models.BigIntegerField(default=0)),
                ("prize_money_relegated", models.BigIntegerField(default=0)),
                ("promotion_spots", models.IntegerField(default=3)),
                ("relegation_spots", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="ClubFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stadium_level", models.IntegerField(default=3)),
                ("stadium_capacity", models.IntegerField(default=5000)),
                ("stadium_upgrade_cost", models.BigIntegerField(default=500000)),
                ("training_level", models.IntegerField(default=3)),
                ("training_upgrade_cost", models.BigIntegerField(default=300000)),
                ("medical_level", models.IntegerField(default=3)),
                ("medical_upgrade_cost", models.BigIntegerField(default=200000)),
                ("youth_level", models.IntegerField(default=3)),
                ("youth_upgrade_cost", models.BigIntegerField(default=250000)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="game.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_season", models.IntegerField(default=2024)),
                ("current_week", models.IntegerField(default=1)),
                ("is_transfer_window_open", models.BooleanField(default=True)),
                ("personal_balance", models.BigIntegerField(default=1000000)),
                ("shortlist", models.JSONField(default=list)),
                (
                    "user_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Game state",
            },
        ),
        migrations.AddField(
            model_name="club",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="game.league",
            ),
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("coaching_attacking", models.IntegerField(default=50)),
                ("coaching_defensive", models.IntegerField(default=50)),
                ("coaching_tactical", models.IntegerField(default=50)),
                ("coaching_mental", models.IntegerField(default=50)),
                ("coaching_youth", models.IntegerField(default=50)),
                ("coaching_ability", models.IntegerField(default=50)),
                (
                    "preferred_formation",
                    models.CharField(
                        choices=[
                            ("4-4-2", "4-4-2"),
                            ("4-3-3", "4-3-3"),
                            ("3-5-2", "3-5-2"),
                            ("4-2-3-1", "4-2-3-1"),
                            ("5-4-1", "5-4-1"),
                            ("4-4-2_DIAMOND", "4-4-2_DIAMOND"),
                        ],
                        default="4-4-2",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("POSSESSION", "POSSESSION"),
                            ("HIGH_PRESSING", "HIGH_PRESSING"),
                            ("COUNTER_ATTACK", "COUNTER_ATTACK"),
                            ("DEFENSIVE", "DEFENSIVE"),
                            ("WING_PLAY", "WING_PLAY"),
                            ("DIRECT", "DIRECT"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                ("pressing", models.IntegerField(default=50)),
                ("creative_freedom", models.IntegerField(default=50)),
                ("personality_discipline", models.IntegerField(default=50)),
                ("personality_loyalty", models.IntegerField(default=50)),
                ("personality_ambition", models.IntegerField(default=50)),
                ("personality_media", models.IntegerField(default=50)),
                ("personality_player_mgmt", models.IntegerField(default=50)),
                ("salary", models.IntegerField(default=5000)),
                ("contract_weeks_remaining", models.IntegerField(default=104)),
                ("morale", models.FloatField(default=70.0)),
                ("relationship_with_chairman", models.FloatField(default=70.0)),
                ("wants_to_leave", models.BooleanField(default=False)),
                ("archetype", models.CharField(default="MOTIVATOR", max_length=30)),
                ("archetype_config", models.JSONField(default=dict)),
                (
                    "club",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to="game.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(default=2024)),
                ("week", models.IntegerField(default=1)),
                ("played", models.BooleanField(default=False)),
                ("home_score", models.IntegerField(default=0)),
                ("away_score", models.IntegerField(default=0)),
                ("events", models.JSONField(default=list)),
                ("home_possession", models.FloatField(default=50.0)),
                ("away_possession", models.FloatField(default=50.0)),
                ("home_shots", models.IntegerField(default=0)),
                ("away_shots", models.IntegerField(default=0)),
                ("home_shots_on_target", models.IntegerField(default=0)),
                ("away_shots_on_target", models.IntegerField(default=0)),
                ("home_xg", models.FloatField(default=0.0)),
                ("away_xg", models.FloatField(default=0.0)),
                ("player_ratings", models.JSONField(default=dict)),
                (
                    "away_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="game.club",
                    ),
                ),
                (
                    "home_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="game.club",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.league"
                    ),
                ),
            ],
            options={
                "ordering": ["season", "week"],
            },
        ),
        migrations.CreateModel(
            name="NewsStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATCH", "MATCH"),
                            ("TRANSFER", "TRANSFER"),
                            ("CLUB", "CLUB"),
                            ("WORLD", "WORLD"),
                            ("FINANCE", "FINANCE"),
                            ("INJURY", "INJURY"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("BREAKING", "BREAKING"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("week", models.IntegerField()),
                ("season", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.IntegerField(default=22)),
                ("nationality", models.CharField(default="English", max_length=50)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "GK"),
                            ("DEF", "DEF"),
                            ("MID", "MID"),
                            ("ATT", "ATT"),
                        ],
                        max_length=5,
                    ),
                ),
                ("archetype", models.CharField(default="", max_length=50)),
                ("overall_rating", models.FloatField(default=50.0)),
                ("potential_rating", models.IntegerField(default=60)),
                ("tech_passing", models.IntegerField(default=50)),
                ("tech_shooting", models.IntegerField(default=50)),
                ("tech_dribbling", models.IntegerField(default=50)),
                ("tech_tackling", models.IntegerField(default=50)),
                ("tech_positioning", models.IntegerField(default=50)),
                ("tech_vision", models.IntegerField(default=50)),
                ("tech_finishing", models.IntegerField(default=50)),
                ("tech_handling", models.IntegerField(default=50)),
                ("tech_reflexes", models.IntegerField(default=50)),
                ("tech_command_of_area", models.IntegerField(default=50)),
                ("tech_rushing_out", models.IntegerField(default=50)),
                ("phys_pace", models.IntegerField(default=50)),
                ("phys_strength", models.IntegerField(default=50)),
                ("phys_stamina", models.IntegerField(default=50)),
                ("phys_agility", models.IntegerField(default=50)),
                ("phys_acceleration", models.IntegerField(default=50)),
                ("ment_leadership", models.IntegerField(default=50)),
                ("ment_composure", models.IntegerField(default=50)),
                ("ment_aggression", models.IntegerField(default=50)),
                ("ment_work_rate", models.IntegerField(default=50)),
                ("ment_decisions", models.IntegerField(default=50)),
                ("ment_determination", models.IntegerField(default=50)),
                ("hidden_professionalism", models.IntegerField(default=50)),
                ("hidden_ambition", models.IntegerField(default=50)),
                ("hidden_loyalty", models.IntegerField(default=50)),
                ("hidden_injury_proneness", models.IntegerField(default=50)),
                ("hidden_temperament", models.IntegerField(default=50)),
                ("hidden_big_match", models.IntegerField(default=50)),
                ("hidden_consistency", models.IntegerField(default=50)),
                ("value", models.BigIntegerField(default=50000)),
                ("wage", models.IntegerField(default=500)),
                ("contract_years", models.IntegerField(default=2)),
                ("morale", models.FloatField(default=70.0)),
                ("fitness", models.FloatField(default=100.0)),
                ("fatigue", models.FloatField(default=0.0)),
                ("is_injured", models.BooleanField(default=False)),
                ("injury_weeks_remaining", models.IntegerField(default=0)),
                ("tactical_familiarity", models.FloatField(default=50.0)),
                ("form", models.JSONField(default=list)),
                ("happiness_contract", models.IntegerField(default=80)),
                ("happiness_playing_time", models.IntegerField(default=80)),
                ("happiness_manager", models.IntegerField(default=80)),
                ("happiness_club_ambition", models.IntegerField(default=80)),
                ("is_transfer_listed", models.BooleanField(default=False)),
                ("is_loan_listed", models.BooleanField(default=False)),
                (
                    "personality",
                    models.CharField(default="PROFESSIONAL", max_length=30),
                ),
                ("appearances", models.IntegerField(default=0)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("is_legend", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="game.club",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_rating"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sponsor_type", models.CharField(max_length=20)),
                ("amount", models.BigIntegerField()),
                ("duration_seasons", models.IntegerField(default=1)),
                ("reputation_required", models.IntegerField(default=0)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="game.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SPORTING_DIRECTOR", "SPORTING_DIRECTOR"),
                            ("SCOUT", "SCOUT"),
                            ("PHYSIO", "PHYSIO"),
                            ("ANALYST", "ANALYST"),
                            ("ACADEMY_COACH", "ACADEMY_COACH"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rating", models.IntegerField(default=50)),
                ("salary", models.IntegerField(default=1000)),
                ("is_applicant", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="game.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoutAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("progress", models.FloatField(default=0.0)),
                ("players_found", models.JSONField(default=list)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scout_assignments",
                        to="game.club",
                    ),
                ),
                (
                    "scout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("negotiation_count", models.IntegerField(default=0)),
                ("created_week", models.IntegerField(default=1)),
                ("created_season", models.IntegerField(default=2024)),
                ("is_player_interested", models.BooleanField(default=True)),
                (
                    "from_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_bids",
                        to="game.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="game.player",
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_bids",
                        to="game.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_type", models.CharField(max_length=30)),
                ("priority", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("suggested_position", models.CharField(blank=True, max_length=5)),
                ("week_requested", models.IntegerField()),
                ("season_requested", models.IntegerField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_requests",
                        to="game.club",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.manager"
                    ),
                ),
            ],
        ),
    ]
