# Generated by Django 5.1.4 on 2026-05-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="training_focus",
            field=models.CharField(
                choices=[
                    ("ATTACKING", "ATTACKING"),
                    ("DEFENSIVE", "DEFENSIVE"),
                    ("PHYSICAL", "PHYSICAL"),
                    ("MENTAL", "MENTAL"),
                    ("BALANCED", "BALANCED"),
                ],
                default="BALANCED",
                max_length=20,
            ),
        ),
    ]
