# Generated by Django 5.1.4 on 2026-05-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_club_training_focus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoutassignment",
            name="players_found",
        ),
        migrations.CreateModel(
            name="ScoutReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_rating", models.FloatField()),
                ("created_week", models.IntegerField()),
                ("created_season", models.IntegerField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="game.scoutassignment",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
            ],
        ),
    ]
