# Generated by Django 5.1.4 on 2026-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_scoutassignment_players_found_scoutreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="personal_balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
