# Generated by Django 5.1.4 on 2026-05-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_manager_personal_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("appearances", models.IntegerField(default=0)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_history",
                        to="game.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season")},
            },
        ),
    ]
