# Generated by Django 5.2.10 on 2026-05-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playerseasonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ment_anticipation',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='ment_bravery',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='ment_concentration',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='ment_off_the_ball',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='ment_teamwork',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='phys_balance',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='phys_jumping_reach',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='phys_natural_fitness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tech_crossing',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tech_first_touch',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tech_heading',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tech_long_shots',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tech_technique',
            field=models.IntegerField(default=50),
        ),
    ]
